In [1]:
import torch
torch.__version__

'2.2.1'

In [3]:
# a zero dimension tensor.
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# a single dimension tensor
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
Tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])

Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [13]:
Tensor.shape

torch.Size([1, 3, 3])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

![example of different tensor dimensions](https://raw.githubusercontent.com/mrdbourke/pytorch-deep-learning/main/images/00-pytorch-different-tensor-dimensions.png)


In [16]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

(tensor([[0.3374, 0.0624, 0.2513, 0.1270],
         [0.1751, 0.5457, 0.8111, 0.2640],
         [0.7527, 0.8036, 0.4866, 0.0962]]),
 torch.float32)

In [17]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [18]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [19]:
ones = torch.ones(size=(3, 4))
ones, ones.dtype

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.float32)

In [20]:
# Create a range of values 0 to 10
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [23]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [24]:
x = torch.tensor([1, 2, 3])
x.shape

torch.Size([3])

In [25]:
x * x

tensor([1, 4, 9])

In [26]:
x @ x

tensor(14)

In [27]:
torch.matmul(x, x)

tensor(14)

In [33]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [34]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

In [35]:
x.argmax(), x.argmin()

(tensor(9), tensor(0))

In [36]:
x.shape

torch.Size([10])

In [48]:
x = x.reshape(1, 10)

In [49]:
x.shape

torch.Size([1, 10])

In [51]:
x[:, 5] = 2
x

tensor([[ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90]])

In [55]:
x_stacked = torch.stack([x, x, x, x], dim=0) 
x_stacked

tensor([[[ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90]],

        [[ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90]],

        [[ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90]],

        [[ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90]]])

In [56]:
x_stacked.shape

torch.Size([4, 1, 10])

In [57]:
x_stacked = torch.stack([x, x, x, x], dim=1) 
x_stacked

tensor([[[ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90],
         [ 0, 10, 20, 30, 40,  2, 60, 70, 80, 90]]])

In [58]:
x_stacked.shape

torch.Size([1, 4, 10])

In [59]:
x.shape

torch.Size([1, 10])

In [62]:
x_squeezed = x.squeeze()
x_squeezed.shape

torch.Size([10])

In [64]:
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed.shape

torch.Size([1, 10])

In [65]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)

x_permuted.shape

torch.Size([3, 224, 224])

In [66]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [68]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [69]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [70]:
x[:, 1, :]

tensor([[4, 5, 6]])

In [71]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [72]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] 

tensor([1, 2, 3])